### ISSUE TITLE
Update docs to reflect new environment variables for command line usage

### ISSUE THREAD

**Issue by galenmarchetti** [kurtosis-tech/kurtosis-docs#21]
if you run `./scripts/buld_and_run.sh help` you get redirected to https://github.com/kurtosis-tech/kurtosis-docs/blob/master/testsuite-details.md but are out of date when it comes to what env variables are available

**Comment by mieubrisse** [comment]
Hey @galenmarchetti can you clarify this? Which `build_and_run` are you talking about?

**Comment by galenmarchetti** [comment]
Ah, clarification: it's the `./scripts/build_and_run.sh` you get after bootstrapping from master on `kurtosis-go`
